title: Nate Stringham # your name (or website title) here
logo: "/images/NateSHeadshot copy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <i class="material-icons">school</i> Pomona College '20 - B.A. Math<br>
  <i class="material-icons">location_on</i> SLC, UT <br>
  <i class="material-icons">directions_run</i> Runner <br>
  <i class="material-icons">email</i> n8stringham@gmail.com
  <br><br>
  This site is a work in progress....
  <br><br>
  <a href="https://n8stringham.github.io/about.html">Another Page</a>
  <br><br>
  <a href="https://www.linkedin.com/in/nathan-stringham/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: #UA-000000-0 # your Google Analytics tracking ID here
